### ISSUE TITLE
failed to load in Linuxsampler

### ISSUE THREAD

**Issue by grammoboy2** [sfzinstruments/MatsHelgesson.MaestroConcertGrandPiano#3]
Caching initial samples...sfz::Engine error: Failed to load instrument, cause: /home/user/linuxaudio/MatsHelgesson.MaestroConcertGrandPiano/Data/Samples/mcg_e_spr_mf.flac: Can't get sample info: System error : No such file or directory.

**Comment by kinwie** [comment]
I added compatibility info to the README.md file, to state this will only supported for sforzando/ARIA Engine.
This issue should be forwarded to LinuxSampler instead for them to track the problems.
So I close this now
