### ISSUE TITLE
The problem with Git hub is...

### ISSUE THREAD

**Issue by 5YNTH3T1K** [sfzinstruments/MatsHelgesson.MaestroConcertGrandPiano#4]
You come here and see there is a lot going on, but where is the download? 

I am interested in the MaestroConcertGrandPiano right, and I know it's a SFZ sample format etc etc. 
Have the SFZ player ready to go in Reaper. 

But where is the "package" ??? and this is the GitHub problem. In most times there is none ! 

Please do us all a favour and make a package and release it. ( all the right stuff in one RAR file is fine ) 

I have no idea how to do this and I am sure the devs do so yeah... help us out mate. : - ) 

Bob.

**Comment by redtide** [comment]
In the main page there is a green button: "Code" -> [Download ZIP](https://github.com/sfzinstruments/MatsHelgesson.MaestroConcertGrandPiano/archive/refs/heads/master.zip)

**Comment by 5YNTH3T1K** [comment]
of course. The code button. I should have guessed.

Mmm  Key 54 at full bore has a bit a bzzz.... if I play around it it's quite hairy.  and 51 . The least played keys on the piano or a slight technical issue. Still, it's very nice. 

The lid control is cool. and the lid open close noises are very cool. It's the little things sometimes ! : -) 

I am not a piano  player but really like them, I mean they are amazing. My work had two Steinway grands. I would play Bach on them. badly. The sustain..  joy. 

Donations ?  How ? 

Thank you! 

Me.

**Comment by redtide** [comment]
> Mmm Key 54 at full bore has a bit a bzzz.... if I play around it it's quite hairy. and 51 . The least played keys on the piano or a slight technical issue. Still, it's very nice.

If this is an issue for you, feel free to open in a dedicated one.

> Donations ? How ?

AFAIK there is no donations management here, instruments are shared by sample instrument makers (directly of with their permissions/original license). @DSmolken: any opinion about this?
